version: '3'

services:
  postgres:
    platform: linux/x86_64
    image: postgres:15
    container_name: kubetsu-postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: kubetsu-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true

