#![cfg_attr(not(test), no_std)]
#![doc = include_str!("../README.md")]

mod macros;

mod id;
/// A ready-made generic ID type, equivalent to `define_id!(pub struct Id<T, U>;)`.
#[deprecated(
    since = "0.6.0",
    note = "Use `kubetsu::define_id!` to define your own ID type instead."
)]
pub use id::Id;

/// Trait implemented by every type generated by [`define_id!`].
///
/// Adapter crates (`kubetsu-serde`, `kubetsu-fake`, `kubetsu-sqlx`,
/// `kubetsu-libsql`) require this trait to ensure that their macros are only
/// used with kubetsu ID types. Its methods mirror the inherent ones every
/// generated type has, so code generic over `T: KubetsuId` can construct,
/// borrow and consume an ID.
pub trait KubetsuId {
    type Inner;
    fn new(inner: Self::Inner) -> Self;
    fn inner(&self) -> &Self::Inner;
    fn into_inner(self) -> Self::Inner;
}
