name: CI

on:
  push:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --features kubetsu-sqlx/any,kubetsu-sqlx/mysql,kubetsu-sqlx/postgres,kubetsu-sqlx/sqlite -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace --features kubetsu-sqlx/any,kubetsu-sqlx/mysql,kubetsu-sqlx/postgres,kubetsu-sqlx/sqlite

  no_std:
    name: Build (no_std)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: thumbv7em-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -p kubetsu-no-std-tests --target thumbv7em-none-eabihf
      - run: cargo clippy -p kubetsu-no-std-tests --target thumbv7em-none-eabihf -- -D warnings
